# 主题配置
theme_color: '#f0f0f0'  # 主题颜色,设置为浅灰色
card_animation: true    # 启用卡片动画效果

# 在 Hexo 的 _config.yml 文件中添加或修改
default_layout: post

# 图片路径设置
post_asset_folder: false
marked:
  prependRoot: true
  postAsset: false

# 用户头像设置
user_avatar: /img/avatar.jpg  # 默认头像路径